// Code generated by wit-bindgen-go. DO NOT EDIT.

package postgres

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// DbErrorShape is used for storage in variant or result types.
type DbErrorShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(DbError{})]byte
}

// QueryErrorShape is used for storage in variant or result types.
type QueryErrorShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(QueryError{})]byte
}

// TupleOptionTupleS64RangeBoundKindOptionTupleS64RangeBoundKindShape is used for storage in variant or result types.
type TupleOptionTupleS64RangeBoundKindOptionTupleS64RangeBoundKindShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof([2]cm.Option[cm.Tuple[int64, RangeBoundKind]]{})]byte
}

// ErrorShape is used for storage in variant or result types.
type ErrorShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(Error{})]byte
}
