// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package postgres represents the imported interface "spin:postgres/postgres@4.0.0".
package postgres

import (
	"go.bytecodealliance.org/cm"
)

// DbError represents the record "spin:postgres/postgres@4.0.0#db-error".
//
//	record db-error {
//		as-text: string,
//		severity: string,
//		code: string,
//		message: string,
//		detail: option<string>,
//		extras: list<tuple<string, string>>,
//	}
type DbError struct {
	_ cm.HostLayout `json:"-"`
	// Stringised version of the error. This is primarily to facilitate migration of older
	// code.
	AsText   string            `json:"as-text"`
	Severity string            `json:"severity"`
	Code     string            `json:"code"`
	Message  string            `json:"message"`
	Detail   cm.Option[string] `json:"detail"`

	// Any error information provided by Postgres and not captured above.
	Extras cm.List[[2]string] `json:"extras"`
}

// QueryError represents the variant "spin:postgres/postgres@4.0.0#query-error".
//
//	variant query-error {
//		text(string),
//		db-error(db-error),
//	}
type QueryError cm.Variant[uint8, DbErrorShape, DbError]

// QueryErrorText returns a [QueryError] of case "text".
//
// An error occurred but we do not have structured info for it
func QueryErrorText(data string) QueryError {
	return cm.New[QueryError](0, data)
}

// Text returns a non-nil *[string] if [QueryError] represents the variant case "text".
func (self *QueryError) Text() *string {
	return cm.Case[string](self, 0)
}

// QueryErrorDbError returns a [QueryError] of case "db-error".
//
// Postgres returned a structured database error
func QueryErrorDbError(data DbError) QueryError {
	return cm.New[QueryError](1, data)
}

// DbError returns a non-nil *[DbError] if [QueryError] represents the variant case "db-error".
func (self *QueryError) DbError() *DbError {
	return cm.Case[DbError](self, 1)
}

var _QueryErrorStrings = [2]string{
	"text",
	"db-error",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v QueryError) String() string {
	return _QueryErrorStrings[v.Tag()]
}

// Error represents the variant "spin:postgres/postgres@4.0.0#error".
//
// Errors related to interacting with a database.
//
//	variant error {
//		connection-failed(string),
//		bad-parameter(string),
//		query-failed(query-error),
//		value-conversion-failed(string),
//		other(string),
//	}
type Error cm.Variant[uint8, QueryErrorShape, QueryError]

// ErrorConnectionFailed returns a [Error] of case "connection-failed".
func ErrorConnectionFailed(data string) Error {
	return cm.New[Error](0, data)
}

// ConnectionFailed returns a non-nil *[string] if [Error] represents the variant case "connection-failed".
func (self *Error) ConnectionFailed() *string {
	return cm.Case[string](self, 0)
}

// ErrorBadParameter returns a [Error] of case "bad-parameter".
func ErrorBadParameter(data string) Error {
	return cm.New[Error](1, data)
}

// BadParameter returns a non-nil *[string] if [Error] represents the variant case "bad-parameter".
func (self *Error) BadParameter() *string {
	return cm.Case[string](self, 1)
}

// ErrorQueryFailed returns a [Error] of case "query-failed".
func ErrorQueryFailed(data QueryError) Error {
	return cm.New[Error](2, data)
}

// QueryFailed returns a non-nil *[QueryError] if [Error] represents the variant case "query-failed".
func (self *Error) QueryFailed() *QueryError {
	return cm.Case[QueryError](self, 2)
}

// ErrorValueConversionFailed returns a [Error] of case "value-conversion-failed".
func ErrorValueConversionFailed(data string) Error {
	return cm.New[Error](3, data)
}

// ValueConversionFailed returns a non-nil *[string] if [Error] represents the variant case "value-conversion-failed".
func (self *Error) ValueConversionFailed() *string {
	return cm.Case[string](self, 3)
}

// ErrorOther returns a [Error] of case "other".
func ErrorOther(data string) Error {
	return cm.New[Error](4, data)
}

// Other returns a non-nil *[string] if [Error] represents the variant case "other".
func (self *Error) Other() *string {
	return cm.Case[string](self, 4)
}

var _ErrorStrings = [5]string{
	"connection-failed",
	"bad-parameter",
	"query-failed",
	"value-conversion-failed",
	"other",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v Error) String() string {
	return _ErrorStrings[v.Tag()]
}

// DbDataType represents the variant "spin:postgres/postgres@4.0.0#db-data-type".
//
// Data types for a database column
//
//	variant db-data-type {
//		boolean,
//		int8,
//		int16,
//		int32,
//		int64,
//		floating32,
//		floating64,
//		str,
//		binary,
//		date,
//		time,
//		datetime,
//		timestamp,
//		uuid,
//		jsonb,
//		decimal,
//		range-int32,
//		range-int64,
//		range-decimal,
//		array-int32,
//		array-int64,
//		array-decimal,
//		array-str,
//		interval,
//		other(string),
//	}
type DbDataType cm.Variant[uint8, string, string]

// DbDataTypeBoolean returns a [DbDataType] of case "boolean".
func DbDataTypeBoolean() DbDataType {
	var data struct{}
	return cm.New[DbDataType](0, data)
}

// Boolean returns true if [DbDataType] represents the variant case "boolean".
func (self *DbDataType) Boolean() bool {
	return self.Tag() == 0
}

// DbDataTypeInt8 returns a [DbDataType] of case "int8".
func DbDataTypeInt8() DbDataType {
	var data struct{}
	return cm.New[DbDataType](1, data)
}

// Int8 returns true if [DbDataType] represents the variant case "int8".
func (self *DbDataType) Int8() bool {
	return self.Tag() == 1
}

// DbDataTypeInt16 returns a [DbDataType] of case "int16".
func DbDataTypeInt16() DbDataType {
	var data struct{}
	return cm.New[DbDataType](2, data)
}

// Int16 returns true if [DbDataType] represents the variant case "int16".
func (self *DbDataType) Int16() bool {
	return self.Tag() == 2
}

// DbDataTypeInt32 returns a [DbDataType] of case "int32".
func DbDataTypeInt32() DbDataType {
	var data struct{}
	return cm.New[DbDataType](3, data)
}

// Int32 returns true if [DbDataType] represents the variant case "int32".
func (self *DbDataType) Int32() bool {
	return self.Tag() == 3
}

// DbDataTypeInt64 returns a [DbDataType] of case "int64".
func DbDataTypeInt64() DbDataType {
	var data struct{}
	return cm.New[DbDataType](4, data)
}

// Int64 returns true if [DbDataType] represents the variant case "int64".
func (self *DbDataType) Int64() bool {
	return self.Tag() == 4
}

// DbDataTypeFloating32 returns a [DbDataType] of case "floating32".
func DbDataTypeFloating32() DbDataType {
	var data struct{}
	return cm.New[DbDataType](5, data)
}

// Floating32 returns true if [DbDataType] represents the variant case "floating32".
func (self *DbDataType) Floating32() bool {
	return self.Tag() == 5
}

// DbDataTypeFloating64 returns a [DbDataType] of case "floating64".
func DbDataTypeFloating64() DbDataType {
	var data struct{}
	return cm.New[DbDataType](6, data)
}

// Floating64 returns true if [DbDataType] represents the variant case "floating64".
func (self *DbDataType) Floating64() bool {
	return self.Tag() == 6
}

// DbDataTypeStr returns a [DbDataType] of case "str".
func DbDataTypeStr() DbDataType {
	var data struct{}
	return cm.New[DbDataType](7, data)
}

// Str returns true if [DbDataType] represents the variant case "str".
func (self *DbDataType) Str() bool {
	return self.Tag() == 7
}

// DbDataTypeBinary returns a [DbDataType] of case "binary".
func DbDataTypeBinary() DbDataType {
	var data struct{}
	return cm.New[DbDataType](8, data)
}

// Binary returns true if [DbDataType] represents the variant case "binary".
func (self *DbDataType) Binary() bool {
	return self.Tag() == 8
}

// DbDataTypeDate returns a [DbDataType] of case "date".
func DbDataTypeDate() DbDataType {
	var data struct{}
	return cm.New[DbDataType](9, data)
}

// Date returns true if [DbDataType] represents the variant case "date".
func (self *DbDataType) Date() bool {
	return self.Tag() == 9
}

// DbDataTypeTime returns a [DbDataType] of case "time".
func DbDataTypeTime() DbDataType {
	var data struct{}
	return cm.New[DbDataType](10, data)
}

// Time returns true if [DbDataType] represents the variant case "time".
func (self *DbDataType) Time() bool {
	return self.Tag() == 10
}

// DbDataTypeDateTime returns a [DbDataType] of case "datetime".
func DbDataTypeDateTime() DbDataType {
	var data struct{}
	return cm.New[DbDataType](11, data)
}

// DateTime returns true if [DbDataType] represents the variant case "datetime".
func (self *DbDataType) DateTime() bool {
	return self.Tag() == 11
}

// DbDataTypeTimestamp returns a [DbDataType] of case "timestamp".
func DbDataTypeTimestamp() DbDataType {
	var data struct{}
	return cm.New[DbDataType](12, data)
}

// Timestamp returns true if [DbDataType] represents the variant case "timestamp".
func (self *DbDataType) Timestamp() bool {
	return self.Tag() == 12
}

// DbDataTypeUUID returns a [DbDataType] of case "uuid".
func DbDataTypeUUID() DbDataType {
	var data struct{}
	return cm.New[DbDataType](13, data)
}

// UUID returns true if [DbDataType] represents the variant case "uuid".
func (self *DbDataType) UUID() bool {
	return self.Tag() == 13
}

// DbDataTypeJsonb returns a [DbDataType] of case "jsonb".
func DbDataTypeJsonb() DbDataType {
	var data struct{}
	return cm.New[DbDataType](14, data)
}

// Jsonb returns true if [DbDataType] represents the variant case "jsonb".
func (self *DbDataType) Jsonb() bool {
	return self.Tag() == 14
}

// DbDataTypeDecimal returns a [DbDataType] of case "decimal".
func DbDataTypeDecimal() DbDataType {
	var data struct{}
	return cm.New[DbDataType](15, data)
}

// Decimal returns true if [DbDataType] represents the variant case "decimal".
func (self *DbDataType) Decimal() bool {
	return self.Tag() == 15
}

// DbDataTypeRangeInt32 returns a [DbDataType] of case "range-int32".
func DbDataTypeRangeInt32() DbDataType {
	var data struct{}
	return cm.New[DbDataType](16, data)
}

// RangeInt32 returns true if [DbDataType] represents the variant case "range-int32".
func (self *DbDataType) RangeInt32() bool {
	return self.Tag() == 16
}

// DbDataTypeRangeInt64 returns a [DbDataType] of case "range-int64".
func DbDataTypeRangeInt64() DbDataType {
	var data struct{}
	return cm.New[DbDataType](17, data)
}

// RangeInt64 returns true if [DbDataType] represents the variant case "range-int64".
func (self *DbDataType) RangeInt64() bool {
	return self.Tag() == 17
}

// DbDataTypeRangeDecimal returns a [DbDataType] of case "range-decimal".
func DbDataTypeRangeDecimal() DbDataType {
	var data struct{}
	return cm.New[DbDataType](18, data)
}

// RangeDecimal returns true if [DbDataType] represents the variant case "range-decimal".
func (self *DbDataType) RangeDecimal() bool {
	return self.Tag() == 18
}

// DbDataTypeArrayInt32 returns a [DbDataType] of case "array-int32".
func DbDataTypeArrayInt32() DbDataType {
	var data struct{}
	return cm.New[DbDataType](19, data)
}

// ArrayInt32 returns true if [DbDataType] represents the variant case "array-int32".
func (self *DbDataType) ArrayInt32() bool {
	return self.Tag() == 19
}

// DbDataTypeArrayInt64 returns a [DbDataType] of case "array-int64".
func DbDataTypeArrayInt64() DbDataType {
	var data struct{}
	return cm.New[DbDataType](20, data)
}

// ArrayInt64 returns true if [DbDataType] represents the variant case "array-int64".
func (self *DbDataType) ArrayInt64() bool {
	return self.Tag() == 20
}

// DbDataTypeArrayDecimal returns a [DbDataType] of case "array-decimal".
func DbDataTypeArrayDecimal() DbDataType {
	var data struct{}
	return cm.New[DbDataType](21, data)
}

// ArrayDecimal returns true if [DbDataType] represents the variant case "array-decimal".
func (self *DbDataType) ArrayDecimal() bool {
	return self.Tag() == 21
}

// DbDataTypeArrayStr returns a [DbDataType] of case "array-str".
func DbDataTypeArrayStr() DbDataType {
	var data struct{}
	return cm.New[DbDataType](22, data)
}

// ArrayStr returns true if [DbDataType] represents the variant case "array-str".
func (self *DbDataType) ArrayStr() bool {
	return self.Tag() == 22
}

// DbDataTypeInterval returns a [DbDataType] of case "interval".
func DbDataTypeInterval() DbDataType {
	var data struct{}
	return cm.New[DbDataType](23, data)
}

// Interval returns true if [DbDataType] represents the variant case "interval".
func (self *DbDataType) Interval() bool {
	return self.Tag() == 23
}

// DbDataTypeOther returns a [DbDataType] of case "other".
func DbDataTypeOther(data string) DbDataType {
	return cm.New[DbDataType](24, data)
}

// Other returns a non-nil *[string] if [DbDataType] represents the variant case "other".
func (self *DbDataType) Other() *string {
	return cm.Case[string](self, 24)
}

var _DbDataTypeStrings = [25]string{
	"boolean",
	"int8",
	"int16",
	"int32",
	"int64",
	"floating32",
	"floating64",
	"str",
	"binary",
	"date",
	"time",
	"datetime",
	"timestamp",
	"uuid",
	"jsonb",
	"decimal",
	"range-int32",
	"range-int64",
	"range-decimal",
	"array-int32",
	"array-int64",
	"array-decimal",
	"array-str",
	"interval",
	"other",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v DbDataType) String() string {
	return _DbDataTypeStrings[v.Tag()]
}

// Interval represents the record "spin:postgres/postgres@4.0.0#interval".
//
//	record interval {
//		micros: s64,
//		days: s32,
//		months: s32,
//	}
type Interval struct {
	_      cm.HostLayout `json:"-"`
	Micros int64         `json:"micros"`
	Days   int32         `json:"days"`
	Months int32         `json:"months"`
}

// Column represents the record "spin:postgres/postgres@4.0.0#column".
//
// A database column
//
//	record column {
//		name: string,
//		data-type: db-data-type,
//	}
type Column struct {
	_        cm.HostLayout `json:"-"`
	Name     string        `json:"name"`
	DataType DbDataType    `json:"data-type"`
}

// RangeBoundKind represents the enum "spin:postgres/postgres@4.0.0#range-bound-kind".
//
// For range types, indicates if each bound is inclusive or exclusive
//
//	enum range-bound-kind {
//		inclusive,
//		exclusive
//	}
type RangeBoundKind uint8

const (
	RangeBoundKindInclusive RangeBoundKind = iota
	RangeBoundKindExclusive
)

var _RangeBoundKindStrings = [2]string{
	"inclusive",
	"exclusive",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e RangeBoundKind) String() string {
	return _RangeBoundKindStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e RangeBoundKind) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *RangeBoundKind) UnmarshalText(text []byte) error {
	return _RangeBoundKindUnmarshalCase(e, text)
}

var _RangeBoundKindUnmarshalCase = cm.CaseUnmarshaler[RangeBoundKind](_RangeBoundKindStrings[:])

// DbValue represents the variant "spin:postgres/postgres@4.0.0#db-value".
//
// Database values
//
//	variant db-value {
//		boolean(bool),
//		int8(s8),
//		int16(s16),
//		int32(s32),
//		int64(s64),
//		floating32(f32),
//		floating64(f64),
//		str(string),
//		binary(list<u8>),
//		date(tuple<s32, u8, u8>),
//		time(tuple<u8, u8, u8, u32>),
//		datetime(tuple<s32, u8, u8, u8, u8, u8, u32>),
//		timestamp(s64),
//		uuid(string),
//		jsonb(list<u8>),
//		decimal(string),
//		range-int32(tuple<option<tuple<s32, range-bound-kind>>, option<tuple<s32, range-bound-kind>>>),
//		range-int64(tuple<option<tuple<s64, range-bound-kind>>, option<tuple<s64, range-bound-kind>>>),
//		range-decimal(tuple<option<tuple<string, range-bound-kind>>, option<tuple<string,
//	range-bound-kind>>>),
//		array-int32(list<option<s32>>),
//		array-int64(list<option<s64>>),
//		array-decimal(list<option<string>>),
//		array-str(list<option<string>>),
//		interval(interval),
//		db-null,
//		unsupported(list<u8>),
//	}
type DbValue cm.Variant[uint8, TupleOptionTupleS64RangeBoundKindOptionTupleS64RangeBoundKindShape, [2]cm.Option[cm.Tuple[int64, RangeBoundKind]]]

// DbValueBoolean returns a [DbValue] of case "boolean".
func DbValueBoolean(data bool) DbValue {
	return cm.New[DbValue](0, data)
}

// Boolean returns a non-nil *[bool] if [DbValue] represents the variant case "boolean".
func (self *DbValue) Boolean() *bool {
	return cm.Case[bool](self, 0)
}

// DbValueInt8 returns a [DbValue] of case "int8".
func DbValueInt8(data int8) DbValue {
	return cm.New[DbValue](1, data)
}

// Int8 returns a non-nil *[int8] if [DbValue] represents the variant case "int8".
func (self *DbValue) Int8() *int8 {
	return cm.Case[int8](self, 1)
}

// DbValueInt16 returns a [DbValue] of case "int16".
func DbValueInt16(data int16) DbValue {
	return cm.New[DbValue](2, data)
}

// Int16 returns a non-nil *[int16] if [DbValue] represents the variant case "int16".
func (self *DbValue) Int16() *int16 {
	return cm.Case[int16](self, 2)
}

// DbValueInt32 returns a [DbValue] of case "int32".
func DbValueInt32(data int32) DbValue {
	return cm.New[DbValue](3, data)
}

// Int32 returns a non-nil *[int32] if [DbValue] represents the variant case "int32".
func (self *DbValue) Int32() *int32 {
	return cm.Case[int32](self, 3)
}

// DbValueInt64 returns a [DbValue] of case "int64".
func DbValueInt64(data int64) DbValue {
	return cm.New[DbValue](4, data)
}

// Int64 returns a non-nil *[int64] if [DbValue] represents the variant case "int64".
func (self *DbValue) Int64() *int64 {
	return cm.Case[int64](self, 4)
}

// DbValueFloating32 returns a [DbValue] of case "floating32".
func DbValueFloating32(data float32) DbValue {
	return cm.New[DbValue](5, data)
}

// Floating32 returns a non-nil *[float32] if [DbValue] represents the variant case "floating32".
func (self *DbValue) Floating32() *float32 {
	return cm.Case[float32](self, 5)
}

// DbValueFloating64 returns a [DbValue] of case "floating64".
func DbValueFloating64(data float64) DbValue {
	return cm.New[DbValue](6, data)
}

// Floating64 returns a non-nil *[float64] if [DbValue] represents the variant case "floating64".
func (self *DbValue) Floating64() *float64 {
	return cm.Case[float64](self, 6)
}

// DbValueStr returns a [DbValue] of case "str".
func DbValueStr(data string) DbValue {
	return cm.New[DbValue](7, data)
}

// Str returns a non-nil *[string] if [DbValue] represents the variant case "str".
func (self *DbValue) Str() *string {
	return cm.Case[string](self, 7)
}

// DbValueBinary returns a [DbValue] of case "binary".
func DbValueBinary(data cm.List[uint8]) DbValue {
	return cm.New[DbValue](8, data)
}

// Binary returns a non-nil *[cm.List[uint8]] if [DbValue] represents the variant case "binary".
func (self *DbValue) Binary() *cm.List[uint8] {
	return cm.Case[cm.List[uint8]](self, 8)
}

// DbValueDate returns a [DbValue] of case "date".
func DbValueDate(data cm.Tuple3[int32, uint8, uint8]) DbValue {
	return cm.New[DbValue](9, data)
}

// Date returns a non-nil *[cm.Tuple3[int32, uint8, uint8]] if [DbValue] represents the variant case "date".
func (self *DbValue) Date() *cm.Tuple3[int32, uint8, uint8] {
	return cm.Case[cm.Tuple3[int32, uint8, uint8]](self, 9)
}

// DbValueTime returns a [DbValue] of case "time".
//
// (year, month, day)
func DbValueTime(data cm.Tuple4[uint8, uint8, uint8, uint32]) DbValue {
	return cm.New[DbValue](10, data)
}

// Time returns a non-nil *[cm.Tuple4[uint8, uint8, uint8, uint32]] if [DbValue] represents the variant case "time".
func (self *DbValue) Time() *cm.Tuple4[uint8, uint8, uint8, uint32] {
	return cm.Case[cm.Tuple4[uint8, uint8, uint8, uint32]](self, 10)
}

// DbValueDateTime returns a [DbValue] of case "datetime".
//
// (hour, minute, second, nanosecond)
// Date-time types are always treated as UTC (without timezone info).
// The instant is represented as a (year, month, day, hour, minute, second, nanosecond)
// tuple.
func DbValueDateTime(data cm.Tuple7[int32, uint8, uint8, uint8, uint8, uint8, uint32]) DbValue {
	return cm.New[DbValue](11, data)
}

// DateTime returns a non-nil *[cm.Tuple7[int32, uint8, uint8, uint8, uint8, uint8, uint32]] if [DbValue] represents the variant case "datetime".
func (self *DbValue) DateTime() *cm.Tuple7[int32, uint8, uint8, uint8, uint8, uint8, uint32] {
	return cm.Case[cm.Tuple7[int32, uint8, uint8, uint8, uint8, uint8, uint32]](self, 11)
}

// DbValueTimestamp returns a [DbValue] of case "timestamp".
//
// Unix timestamp (seconds since epoch)
func DbValueTimestamp(data int64) DbValue {
	return cm.New[DbValue](12, data)
}

// Timestamp returns a non-nil *[int64] if [DbValue] represents the variant case "timestamp".
func (self *DbValue) Timestamp() *int64 {
	return cm.Case[int64](self, 12)
}

// DbValueUUID returns a [DbValue] of case "uuid".
func DbValueUUID(data string) DbValue {
	return cm.New[DbValue](13, data)
}

// UUID returns a non-nil *[string] if [DbValue] represents the variant case "uuid".
func (self *DbValue) UUID() *string {
	return cm.Case[string](self, 13)
}

// DbValueJsonb returns a [DbValue] of case "jsonb".
func DbValueJsonb(data cm.List[uint8]) DbValue {
	return cm.New[DbValue](14, data)
}

// Jsonb returns a non-nil *[cm.List[uint8]] if [DbValue] represents the variant case "jsonb".
func (self *DbValue) Jsonb() *cm.List[uint8] {
	return cm.Case[cm.List[uint8]](self, 14)
}

// DbValueDecimal returns a [DbValue] of case "decimal".
func DbValueDecimal(data string) DbValue {
	return cm.New[DbValue](15, data)
}

// Decimal returns a non-nil *[string] if [DbValue] represents the variant case "decimal".
func (self *DbValue) Decimal() *string {
	return cm.Case[string](self, 15)
}

// DbValueRangeInt32 returns a [DbValue] of case "range-int32".
//
// I admit defeat. Base 10
func DbValueRangeInt32(data [2]cm.Option[cm.Tuple[int32, RangeBoundKind]]) DbValue {
	return cm.New[DbValue](16, data)
}

// RangeInt32 returns a non-nil *[[2]cm.Option[cm.Tuple[int32, RangeBoundKind]]] if [DbValue] represents the variant case "range-int32".
func (self *DbValue) RangeInt32() *[2]cm.Option[cm.Tuple[int32, RangeBoundKind]] {
	return cm.Case[[2]cm.Option[cm.Tuple[int32, RangeBoundKind]]](self, 16)
}

// DbValueRangeInt64 returns a [DbValue] of case "range-int64".
func DbValueRangeInt64(data [2]cm.Option[cm.Tuple[int64, RangeBoundKind]]) DbValue {
	return cm.New[DbValue](17, data)
}

// RangeInt64 returns a non-nil *[[2]cm.Option[cm.Tuple[int64, RangeBoundKind]]] if [DbValue] represents the variant case "range-int64".
func (self *DbValue) RangeInt64() *[2]cm.Option[cm.Tuple[int64, RangeBoundKind]] {
	return cm.Case[[2]cm.Option[cm.Tuple[int64, RangeBoundKind]]](self, 17)
}

// DbValueRangeDecimal returns a [DbValue] of case "range-decimal".
func DbValueRangeDecimal(data [2]cm.Option[cm.Tuple[string, RangeBoundKind]]) DbValue {
	return cm.New[DbValue](18, data)
}

// RangeDecimal returns a non-nil *[[2]cm.Option[cm.Tuple[string, RangeBoundKind]]] if [DbValue] represents the variant case "range-decimal".
func (self *DbValue) RangeDecimal() *[2]cm.Option[cm.Tuple[string, RangeBoundKind]] {
	return cm.Case[[2]cm.Option[cm.Tuple[string, RangeBoundKind]]](self, 18)
}

// DbValueArrayInt32 returns a [DbValue] of case "array-int32".
func DbValueArrayInt32(data cm.List[cm.Option[int32]]) DbValue {
	return cm.New[DbValue](19, data)
}

// ArrayInt32 returns a non-nil *[cm.List[cm.Option[int32]]] if [DbValue] represents the variant case "array-int32".
func (self *DbValue) ArrayInt32() *cm.List[cm.Option[int32]] {
	return cm.Case[cm.List[cm.Option[int32]]](self, 19)
}

// DbValueArrayInt64 returns a [DbValue] of case "array-int64".
func DbValueArrayInt64(data cm.List[cm.Option[int64]]) DbValue {
	return cm.New[DbValue](20, data)
}

// ArrayInt64 returns a non-nil *[cm.List[cm.Option[int64]]] if [DbValue] represents the variant case "array-int64".
func (self *DbValue) ArrayInt64() *cm.List[cm.Option[int64]] {
	return cm.Case[cm.List[cm.Option[int64]]](self, 20)
}

// DbValueArrayDecimal returns a [DbValue] of case "array-decimal".
func DbValueArrayDecimal(data cm.List[cm.Option[string]]) DbValue {
	return cm.New[DbValue](21, data)
}

// ArrayDecimal returns a non-nil *[cm.List[cm.Option[string]]] if [DbValue] represents the variant case "array-decimal".
func (self *DbValue) ArrayDecimal() *cm.List[cm.Option[string]] {
	return cm.Case[cm.List[cm.Option[string]]](self, 21)
}

// DbValueArrayStr returns a [DbValue] of case "array-str".
func DbValueArrayStr(data cm.List[cm.Option[string]]) DbValue {
	return cm.New[DbValue](22, data)
}

// ArrayStr returns a non-nil *[cm.List[cm.Option[string]]] if [DbValue] represents the variant case "array-str".
func (self *DbValue) ArrayStr() *cm.List[cm.Option[string]] {
	return cm.Case[cm.List[cm.Option[string]]](self, 22)
}

// DbValueInterval returns a [DbValue] of case "interval".
func DbValueInterval(data Interval) DbValue {
	return cm.New[DbValue](23, data)
}

// Interval returns a non-nil *[Interval] if [DbValue] represents the variant case "interval".
func (self *DbValue) Interval() *Interval {
	return cm.Case[Interval](self, 23)
}

// DbValueDbNull returns a [DbValue] of case "db-null".
func DbValueDbNull() DbValue {
	var data struct{}
	return cm.New[DbValue](24, data)
}

// DbNull returns true if [DbValue] represents the variant case "db-null".
func (self *DbValue) DbNull() bool {
	return self.Tag() == 24
}

// DbValueUnsupported returns a [DbValue] of case "unsupported".
func DbValueUnsupported(data cm.List[uint8]) DbValue {
	return cm.New[DbValue](25, data)
}

// Unsupported returns a non-nil *[cm.List[uint8]] if [DbValue] represents the variant case "unsupported".
func (self *DbValue) Unsupported() *cm.List[uint8] {
	return cm.Case[cm.List[uint8]](self, 25)
}

var _DbValueStrings = [26]string{
	"boolean",
	"int8",
	"int16",
	"int32",
	"int64",
	"floating32",
	"floating64",
	"str",
	"binary",
	"date",
	"time",
	"datetime",
	"timestamp",
	"uuid",
	"jsonb",
	"decimal",
	"range-int32",
	"range-int64",
	"range-decimal",
	"array-int32",
	"array-int64",
	"array-decimal",
	"array-str",
	"interval",
	"db-null",
	"unsupported",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v DbValue) String() string {
	return _DbValueStrings[v.Tag()]
}

// ParameterValue represents the variant "spin:postgres/postgres@4.0.0#parameter-value".
//
// Values used in parameterized queries
//
//	variant parameter-value {
//		boolean(bool),
//		int8(s8),
//		int16(s16),
//		int32(s32),
//		int64(s64),
//		floating32(f32),
//		floating64(f64),
//		str(string),
//		binary(list<u8>),
//		date(tuple<s32, u8, u8>),
//		time(tuple<u8, u8, u8, u32>),
//		datetime(tuple<s32, u8, u8, u8, u8, u8, u32>),
//		timestamp(s64),
//		uuid(string),
//		jsonb(list<u8>),
//		decimal(string),
//		range-int32(tuple<option<tuple<s32, range-bound-kind>>, option<tuple<s32, range-bound-kind>>>),
//		range-int64(tuple<option<tuple<s64, range-bound-kind>>, option<tuple<s64, range-bound-kind>>>),
//		range-decimal(tuple<option<tuple<string, range-bound-kind>>, option<tuple<string,
//	range-bound-kind>>>),
//		array-int32(list<option<s32>>),
//		array-int64(list<option<s64>>),
//		array-decimal(list<option<string>>),
//		array-str(list<option<string>>),
//		interval(interval),
//		db-null,
//	}
type ParameterValue cm.Variant[uint8, TupleOptionTupleS64RangeBoundKindOptionTupleS64RangeBoundKindShape, [2]cm.Option[cm.Tuple[int64, RangeBoundKind]]]

// ParameterValueBoolean returns a [ParameterValue] of case "boolean".
func ParameterValueBoolean(data bool) ParameterValue {
	return cm.New[ParameterValue](0, data)
}

// Boolean returns a non-nil *[bool] if [ParameterValue] represents the variant case "boolean".
func (self *ParameterValue) Boolean() *bool {
	return cm.Case[bool](self, 0)
}

// ParameterValueInt8 returns a [ParameterValue] of case "int8".
func ParameterValueInt8(data int8) ParameterValue {
	return cm.New[ParameterValue](1, data)
}

// Int8 returns a non-nil *[int8] if [ParameterValue] represents the variant case "int8".
func (self *ParameterValue) Int8() *int8 {
	return cm.Case[int8](self, 1)
}

// ParameterValueInt16 returns a [ParameterValue] of case "int16".
func ParameterValueInt16(data int16) ParameterValue {
	return cm.New[ParameterValue](2, data)
}

// Int16 returns a non-nil *[int16] if [ParameterValue] represents the variant case "int16".
func (self *ParameterValue) Int16() *int16 {
	return cm.Case[int16](self, 2)
}

// ParameterValueInt32 returns a [ParameterValue] of case "int32".
func ParameterValueInt32(data int32) ParameterValue {
	return cm.New[ParameterValue](3, data)
}

// Int32 returns a non-nil *[int32] if [ParameterValue] represents the variant case "int32".
func (self *ParameterValue) Int32() *int32 {
	return cm.Case[int32](self, 3)
}

// ParameterValueInt64 returns a [ParameterValue] of case "int64".
func ParameterValueInt64(data int64) ParameterValue {
	return cm.New[ParameterValue](4, data)
}

// Int64 returns a non-nil *[int64] if [ParameterValue] represents the variant case "int64".
func (self *ParameterValue) Int64() *int64 {
	return cm.Case[int64](self, 4)
}

// ParameterValueFloating32 returns a [ParameterValue] of case "floating32".
func ParameterValueFloating32(data float32) ParameterValue {
	return cm.New[ParameterValue](5, data)
}

// Floating32 returns a non-nil *[float32] if [ParameterValue] represents the variant case "floating32".
func (self *ParameterValue) Floating32() *float32 {
	return cm.Case[float32](self, 5)
}

// ParameterValueFloating64 returns a [ParameterValue] of case "floating64".
func ParameterValueFloating64(data float64) ParameterValue {
	return cm.New[ParameterValue](6, data)
}

// Floating64 returns a non-nil *[float64] if [ParameterValue] represents the variant case "floating64".
func (self *ParameterValue) Floating64() *float64 {
	return cm.Case[float64](self, 6)
}

// ParameterValueStr returns a [ParameterValue] of case "str".
func ParameterValueStr(data string) ParameterValue {
	return cm.New[ParameterValue](7, data)
}

// Str returns a non-nil *[string] if [ParameterValue] represents the variant case "str".
func (self *ParameterValue) Str() *string {
	return cm.Case[string](self, 7)
}

// ParameterValueBinary returns a [ParameterValue] of case "binary".
func ParameterValueBinary(data cm.List[uint8]) ParameterValue {
	return cm.New[ParameterValue](8, data)
}

// Binary returns a non-nil *[cm.List[uint8]] if [ParameterValue] represents the variant case "binary".
func (self *ParameterValue) Binary() *cm.List[uint8] {
	return cm.Case[cm.List[uint8]](self, 8)
}

// ParameterValueDate returns a [ParameterValue] of case "date".
func ParameterValueDate(data cm.Tuple3[int32, uint8, uint8]) ParameterValue {
	return cm.New[ParameterValue](9, data)
}

// Date returns a non-nil *[cm.Tuple3[int32, uint8, uint8]] if [ParameterValue] represents the variant case "date".
func (self *ParameterValue) Date() *cm.Tuple3[int32, uint8, uint8] {
	return cm.Case[cm.Tuple3[int32, uint8, uint8]](self, 9)
}

// ParameterValueTime returns a [ParameterValue] of case "time".
//
// (year, month, day)
func ParameterValueTime(data cm.Tuple4[uint8, uint8, uint8, uint32]) ParameterValue {
	return cm.New[ParameterValue](10, data)
}

// Time returns a non-nil *[cm.Tuple4[uint8, uint8, uint8, uint32]] if [ParameterValue] represents the variant case "time".
func (self *ParameterValue) Time() *cm.Tuple4[uint8, uint8, uint8, uint32] {
	return cm.Case[cm.Tuple4[uint8, uint8, uint8, uint32]](self, 10)
}

// ParameterValueDateTime returns a [ParameterValue] of case "datetime".
//
// (hour, minute, second, nanosecond)
// Date-time types are always treated as UTC (without timezone info).
// The instant is represented as a (year, month, day, hour, minute, second, nanosecond)
// tuple.
func ParameterValueDateTime(data cm.Tuple7[int32, uint8, uint8, uint8, uint8, uint8, uint32]) ParameterValue {
	return cm.New[ParameterValue](11, data)
}

// DateTime returns a non-nil *[cm.Tuple7[int32, uint8, uint8, uint8, uint8, uint8, uint32]] if [ParameterValue] represents the variant case "datetime".
func (self *ParameterValue) DateTime() *cm.Tuple7[int32, uint8, uint8, uint8, uint8, uint8, uint32] {
	return cm.Case[cm.Tuple7[int32, uint8, uint8, uint8, uint8, uint8, uint32]](self, 11)
}

// ParameterValueTimestamp returns a [ParameterValue] of case "timestamp".
//
// Unix timestamp (seconds since epoch)
func ParameterValueTimestamp(data int64) ParameterValue {
	return cm.New[ParameterValue](12, data)
}

// Timestamp returns a non-nil *[int64] if [ParameterValue] represents the variant case "timestamp".
func (self *ParameterValue) Timestamp() *int64 {
	return cm.Case[int64](self, 12)
}

// ParameterValueUUID returns a [ParameterValue] of case "uuid".
func ParameterValueUUID(data string) ParameterValue {
	return cm.New[ParameterValue](13, data)
}

// UUID returns a non-nil *[string] if [ParameterValue] represents the variant case "uuid".
func (self *ParameterValue) UUID() *string {
	return cm.Case[string](self, 13)
}

// ParameterValueJsonb returns a [ParameterValue] of case "jsonb".
func ParameterValueJsonb(data cm.List[uint8]) ParameterValue {
	return cm.New[ParameterValue](14, data)
}

// Jsonb returns a non-nil *[cm.List[uint8]] if [ParameterValue] represents the variant case "jsonb".
func (self *ParameterValue) Jsonb() *cm.List[uint8] {
	return cm.Case[cm.List[uint8]](self, 14)
}

// ParameterValueDecimal returns a [ParameterValue] of case "decimal".
func ParameterValueDecimal(data string) ParameterValue {
	return cm.New[ParameterValue](15, data)
}

// Decimal returns a non-nil *[string] if [ParameterValue] represents the variant case "decimal".
func (self *ParameterValue) Decimal() *string {
	return cm.Case[string](self, 15)
}

// ParameterValueRangeInt32 returns a [ParameterValue] of case "range-int32".
//
// base 10
func ParameterValueRangeInt32(data [2]cm.Option[cm.Tuple[int32, RangeBoundKind]]) ParameterValue {
	return cm.New[ParameterValue](16, data)
}

// RangeInt32 returns a non-nil *[[2]cm.Option[cm.Tuple[int32, RangeBoundKind]]] if [ParameterValue] represents the variant case "range-int32".
func (self *ParameterValue) RangeInt32() *[2]cm.Option[cm.Tuple[int32, RangeBoundKind]] {
	return cm.Case[[2]cm.Option[cm.Tuple[int32, RangeBoundKind]]](self, 16)
}

// ParameterValueRangeInt64 returns a [ParameterValue] of case "range-int64".
func ParameterValueRangeInt64(data [2]cm.Option[cm.Tuple[int64, RangeBoundKind]]) ParameterValue {
	return cm.New[ParameterValue](17, data)
}

// RangeInt64 returns a non-nil *[[2]cm.Option[cm.Tuple[int64, RangeBoundKind]]] if [ParameterValue] represents the variant case "range-int64".
func (self *ParameterValue) RangeInt64() *[2]cm.Option[cm.Tuple[int64, RangeBoundKind]] {
	return cm.Case[[2]cm.Option[cm.Tuple[int64, RangeBoundKind]]](self, 17)
}

// ParameterValueRangeDecimal returns a [ParameterValue] of case "range-decimal".
func ParameterValueRangeDecimal(data [2]cm.Option[cm.Tuple[string, RangeBoundKind]]) ParameterValue {
	return cm.New[ParameterValue](18, data)
}

// RangeDecimal returns a non-nil *[[2]cm.Option[cm.Tuple[string, RangeBoundKind]]] if [ParameterValue] represents the variant case "range-decimal".
func (self *ParameterValue) RangeDecimal() *[2]cm.Option[cm.Tuple[string, RangeBoundKind]] {
	return cm.Case[[2]cm.Option[cm.Tuple[string, RangeBoundKind]]](self, 18)
}

// ParameterValueArrayInt32 returns a [ParameterValue] of case "array-int32".
func ParameterValueArrayInt32(data cm.List[cm.Option[int32]]) ParameterValue {
	return cm.New[ParameterValue](19, data)
}

// ArrayInt32 returns a non-nil *[cm.List[cm.Option[int32]]] if [ParameterValue] represents the variant case "array-int32".
func (self *ParameterValue) ArrayInt32() *cm.List[cm.Option[int32]] {
	return cm.Case[cm.List[cm.Option[int32]]](self, 19)
}

// ParameterValueArrayInt64 returns a [ParameterValue] of case "array-int64".
func ParameterValueArrayInt64(data cm.List[cm.Option[int64]]) ParameterValue {
	return cm.New[ParameterValue](20, data)
}

// ArrayInt64 returns a non-nil *[cm.List[cm.Option[int64]]] if [ParameterValue] represents the variant case "array-int64".
func (self *ParameterValue) ArrayInt64() *cm.List[cm.Option[int64]] {
	return cm.Case[cm.List[cm.Option[int64]]](self, 20)
}

// ParameterValueArrayDecimal returns a [ParameterValue] of case "array-decimal".
func ParameterValueArrayDecimal(data cm.List[cm.Option[string]]) ParameterValue {
	return cm.New[ParameterValue](21, data)
}

// ArrayDecimal returns a non-nil *[cm.List[cm.Option[string]]] if [ParameterValue] represents the variant case "array-decimal".
func (self *ParameterValue) ArrayDecimal() *cm.List[cm.Option[string]] {
	return cm.Case[cm.List[cm.Option[string]]](self, 21)
}

// ParameterValueArrayStr returns a [ParameterValue] of case "array-str".
func ParameterValueArrayStr(data cm.List[cm.Option[string]]) ParameterValue {
	return cm.New[ParameterValue](22, data)
}

// ArrayStr returns a non-nil *[cm.List[cm.Option[string]]] if [ParameterValue] represents the variant case "array-str".
func (self *ParameterValue) ArrayStr() *cm.List[cm.Option[string]] {
	return cm.Case[cm.List[cm.Option[string]]](self, 22)
}

// ParameterValueInterval returns a [ParameterValue] of case "interval".
func ParameterValueInterval(data Interval) ParameterValue {
	return cm.New[ParameterValue](23, data)
}

// Interval returns a non-nil *[Interval] if [ParameterValue] represents the variant case "interval".
func (self *ParameterValue) Interval() *Interval {
	return cm.Case[Interval](self, 23)
}

// ParameterValueDbNull returns a [ParameterValue] of case "db-null".
func ParameterValueDbNull() ParameterValue {
	var data struct{}
	return cm.New[ParameterValue](24, data)
}

// DbNull returns true if [ParameterValue] represents the variant case "db-null".
func (self *ParameterValue) DbNull() bool {
	return self.Tag() == 24
}

var _ParameterValueStrings = [25]string{
	"boolean",
	"int8",
	"int16",
	"int32",
	"int64",
	"floating32",
	"floating64",
	"str",
	"binary",
	"date",
	"time",
	"datetime",
	"timestamp",
	"uuid",
	"jsonb",
	"decimal",
	"range-int32",
	"range-int64",
	"range-decimal",
	"array-int32",
	"array-int64",
	"array-decimal",
	"array-str",
	"interval",
	"db-null",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v ParameterValue) String() string {
	return _ParameterValueStrings[v.Tag()]
}

// Row represents the list "spin:postgres/postgres@4.0.0#row".
//
// A database row
//
//	type row = list<db-value>
type Row cm.List[DbValue]

// RowSet represents the record "spin:postgres/postgres@4.0.0#row-set".
//
// A set of database rows
//
//	record row-set {
//		columns: list<column>,
//		rows: list<row>,
//	}
type RowSet struct {
	_       cm.HostLayout   `json:"-"`
	Columns cm.List[Column] `json:"columns"`
	Rows    cm.List[Row]    `json:"rows"`
}

// Connection represents the imported resource "spin:postgres/postgres@4.0.0#connection".
//
// A connection to a postgres database.
//
//	resource connection
type Connection cm.Resource

// ResourceDrop represents the imported resource-drop for resource "connection".
//
// Drops a resource handle.
//
//go:nosplit
func (self Connection) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_ConnectionResourceDrop((uint32)(self0))
	return
}

// ConnectionOpen represents the imported static function "open".
//
// Open a connection to the Postgres instance at `address`.
//
//	open: static func(address: string) -> result<connection, error>
//
//go:nosplit
func ConnectionOpen(address string) (result cm.Result[ErrorShape, Connection, Error]) {
	address0, address1 := cm.LowerString(address)
	wasmimport_ConnectionOpen((*uint8)(address0), (uint32)(address1), &result)
	return
}

// Execute represents the imported method "execute".
//
// Execute command to the database.
//
//	execute: func(statement: string, params: list<parameter-value>) -> result<u64,
//	error>
//
//go:nosplit
func (self Connection) Execute(statement string, params cm.List[ParameterValue]) (result cm.Result[ErrorShape, uint64, Error]) {
	self0 := cm.Reinterpret[uint32](self)
	statement0, statement1 := cm.LowerString(statement)
	params0, params1 := cm.LowerList(params)
	wasmimport_ConnectionExecute((uint32)(self0), (*uint8)(statement0), (uint32)(statement1), (*ParameterValue)(params0), (uint32)(params1), &result)
	return
}

// Query represents the imported method "query".
//
// Query the database.
//
//	query: func(statement: string, params: list<parameter-value>) -> result<row-set,
//	error>
//
//go:nosplit
func (self Connection) Query(statement string, params cm.List[ParameterValue]) (result cm.Result[ErrorShape, RowSet, Error]) {
	self0 := cm.Reinterpret[uint32](self)
	statement0, statement1 := cm.LowerString(statement)
	params0, params1 := cm.LowerList(params)
	wasmimport_ConnectionQuery((uint32)(self0), (*uint8)(statement0), (uint32)(statement1), (*ParameterValue)(params0), (uint32)(params1), &result)
	return
}
