spin_manifest_version = 2

[application]
authors = ["Adam Reese <adam@reese.io>"]
description = ""
name = "tinygo-sqlite"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "tinygo-sqlite"

[component.tinygo-sqlite]
source = "main.wasm"
allowed_outbound_hosts = []
sqlite_databases = ["default"]
[component.tinygo-sqlite.build]
command = "tinygo build -target=wasi -gc=leaking -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
