spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "A simple Spin application written in (Tiny)Go that performs outbound HTTP requests."
name = "spin-tinygo-outbound-http"
version = "1.0.0"

[[trigger.http]]
route = "/hello"
component = "tinygo-hello"

[[trigger.http]]
route = "/outbound-http-to-same-app"
component = "outbound-http-to-same-app"

[component.tinygo-hello]
source = "tinygo-hello/main.wasm"
allowed_outbound_hosts = [
    "https://random-data-api.fermyon.app:443",
    "https://postman-echo.com:443",
]
[component.tinygo-hello.build]
workdir = "tinygo-hello"
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"

[component.outbound-http-to-same-app]
source = "outbound-http-to-same-app/main.wasm"
# Use self to make outbound requests to components in the same Spin application.
allowed_outbound_hosts = ["http://self"]
[component.outbound-http-to-same-app.build]
workdir = "outbound-http-to-same-app"
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
