// Code generated by wit-bindgen-go. DO NOT EDIT.

package sqlite

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "spin:sqlite@3.0.0".

//go:wasmimport spin:sqlite/sqlite@3.0.0 [resource-drop]connection
//go:noescape
func wasmimport_ConnectionResourceDrop(self0 uint32)

//go:wasmimport spin:sqlite/sqlite@3.0.0 [static]connection.open
//go:noescape
func wasmimport_ConnectionOpen(database0 *uint8, database1 uint32, result *cm.Result[ErrorShape, Connection, Error])

//go:wasmimport spin:sqlite/sqlite@3.0.0 [method]connection.changes
//go:noescape
func wasmimport_ConnectionChanges(self0 uint32) (result0 uint64)

//go:wasmimport spin:sqlite/sqlite@3.0.0 [method]connection.execute
//go:noescape
func wasmimport_ConnectionExecute(self0 uint32, statement0 *uint8, statement1 uint32, parameters0 *Value, parameters1 uint32, result *cm.Result[QueryResultShape, QueryResult, Error])

//go:wasmimport spin:sqlite/sqlite@3.0.0 [method]connection.last-insert-rowid
//go:noescape
func wasmimport_ConnectionLastInsertRowid(self0 uint32) (result0 uint64)
